import test from 'node:test';
import assert from 'node:assert/strict';
import { mediaCapability, generateMediaOutput } from '../server/ai-media-output.mjs';

const config = { baseUrl: 'https://api.minimaxi.com/anthropic', apiKey: 'fixture-only' }, signal = new AbortController().signal;
const png = Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+j8L8AAAAASUVORK5CYII=', 'base64');
test('image output uses the official media endpoint and contains only validated generated bytes', async () => {
  let request;
  const image = await generateMediaOutput(config, { type: 'image', prompt: '一只卡通小猫' }, signal, async (url, options) => {
    request = { url, options }; return Response.json({ base_resp: { status_code: 0 }, data: { image_base64: [png.toString('base64')] } });
  });
  assert.equal(request.url, 'https://api.minimaxi.com/v1/image_generation');
  assert.equal(JSON.parse(request.options.body).model, 'image-01'); assert.equal(request.options.redirect, 'error');
  assert.equal(image.type, 'image/png'); assert.equal(image.mediaType, 'image');
  assert.deepEqual(Buffer.from(image.data, 'base64'), png); assert.match(image.name, /^AI合成-[a-f0-9-]+\.png$/);
});
test('audio output handles MiniMax hex data as a synthetic MP3 file', async () => {
  const mp3 = Buffer.from('ID3 fixture audio'), audio = await generateMediaOutput(config, { type: 'audio', text: '下午好' }, signal,
    async () => Response.json({ base_resp: { status_code: 0 }, data: { audio: mp3.toString('hex') } }));
  assert.equal(audio.type, 'audio/mpeg'); assert.equal(audio.mediaType, 'audio'); assert.deepEqual(Buffer.from(audio.data, 'base64'), mp3);
  assert.match(audio.name, /^AI-generated-[a-f0-9-]{36}\.mp3$/); assert.equal(Buffer.byteLength(audio.name), audio.name.length);
});
test('media never follows model URLs, supports video or ignores provider errors', async () => {
  assert.equal(mediaCapability({ baseUrl: 'https://models.example.test/v1' }), null);
  for (const item of [{ type: 'video', prompt: 'test' }, { type: 'image', prompt: '' }]) await assert.rejects(generateMediaOutput(config, item, signal));
  await assert.rejects(generateMediaOutput(config, { type: 'image', prompt: 'test' }, signal, async () => new Response('', { status: 403 })), /权限不足/);
  await assert.rejects(generateMediaOutput(config, { type: 'image', prompt: 'test' }, signal, async () => Response.json({ base_resp: { status_code: 1008 }, data: { image_urls: ['https://untrusted.test/a.png'] } })), /媒体生成未成功/);
  await assert.rejects(generateMediaOutput(config, { type: 'image', prompt: 'test' }, signal, async () => Response.json({ data: { image_base64: [Buffer.from('not an image').toString('base64')] } })), /校验失败/);
});

test('unsafe speech is rejected before contacting TTS even when called outside the reply path', async () => {
  let calls = 0;
  const fetcher = async () => { calls++; return Response.json({ data: { audio: Buffer.from('ID3 fixture audio').toString('hex') } }); };
  await assert.rejects(generateMediaOutput(config, { type: 'audio', text: '我是一个机器人' }, signal, fetcher), /身份规则/);
  await assert.rejects(generateMediaOutput(config, { type: 'audio', text: '任务已执行完成' }, signal, fetcher), /未核实/);
  assert.equal(calls, 0);
  await generateMediaOutput(config, { type: 'audio', text: '我是AI代为回复' }, signal, fetcher, { allowIdentity: true });
  assert.equal(calls, 1);
});
