import React, {useEffect,useState} from 'react';
import {Sparkle,ChatCircleText,PaperPlaneTilt,ClockCounterClockwise,SlidersHorizontal,MagnifyingGlass,ArrowLeft,CaretRight,Users,User,ArrowClockwise,Check,ShieldCheck,Lightning,Eye} from '@phosphor-icons/react';
const contacts=[{id:'chen',name:'陈小雨',note:'朋友',color:'purple'},{id:'lin',name:'林一',note:'同事',color:'blue'},{id:'zhou',name:'周末',note:'朋友',color:'peach'},{id:'xu',name:'许知远',note:'同事',color:'teal'},{id:'family',name:'家人群',note:'群聊 · 6 人',group:true,color:'purple'},{id:'design',name:'产品设计讨论',note:'群聊 · 12 人',group:true,color:'blue'}];
const pages=[['reply','自动回复',ChatCircleText],['proactive','主动聊天',PaperPlaneTilt],['activity','运行记录',ClockCounterClockwise],['provider','模型设置',SlidersHorizontal]];
const defaults={enabled:true,multi:true,judge:true,atMe:true,atAll:false,realtime:false,style:'自然亲切',goal:'像平时聊天一样自然回复，语气轻松、友好。\n工作相关的问题简洁明确，不确定的事情先向我确认。'};
function Toggle({label,value,change,disabled}){return <button type="button" role="switch" aria-label={label} aria-checked={value} disabled={disabled} className={'switch '+(value?'on':'')} onClick={()=>change(!value)}><span/></button>}
function Avatar({p,large}){return <span className={'avatar '+p.color+(large?' large':'')}>{p.group?<Users size={large?28:21}/>:p.name.slice(0,1)}</span>}
function load(){try{return JSON.parse(localStorage.getItem('qibox-blue-preview')||'{}')}catch{return {}}}
export function App(){
 const [page,setPage]=useState('reply'),[kind,setKind]=useState(false),[search,setSearch]=useState(''),[selected,setSelected]=useState('chen'),[master,setMaster]=useState(true),[settings,setSettings]=useState(load),[notice,setNotice]=useState(''),[detail,setDetail]=useState(false),[modal,setModal]=useState(''),[events,setEvents]=useState([]),[filter,setFilter]=useState('');
 const [recipients,setRecipients]=useState(['chen']),[purpose,setPurpose]=useState(''),[task,setTask]=useState('idle'),[provider,setProvider]=useState('DeepSeek'),[base,setBase]=useState('https://api.deepseek.com/v1'),[model,setModel]=useState('deepseek-chat'),[reveal,setReveal]=useState(false);
 useEffect(()=>{
  if(!modal)return;
  const previous=document.activeElement, dialog=document.querySelector('[role="dialog"]');
  const controls=[...dialog.querySelectorAll('button,select,input,textarea')];
  controls[0]?.focus();
  const handle=event=>{if(event.key==='Escape'){event.preventDefault();setModal('')}
   if(event.key==='Tab'){const first=controls[0],last=controls.at(-1);if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus()}}};
  document.addEventListener('keydown',handle);
  return()=>{document.removeEventListener('keydown',handle);previous?.focus()};
 },[modal]);
 const person=contacts.find(p=>p.id===selected),value={...defaults,...settings[selected]},title=pages.find(p=>p[0]===page)[1];
 const update=(key,v)=>setSettings(prev=>({...prev,[selected]:{...defaults,...prev[selected],[key]:v}}));
 const toast=text=>{setNotice(text);clearTimeout(window.previewNotice);window.previewNotice=setTimeout(()=>setNotice(''),4000)};
 const log=(who,result)=>setEvents(prev=>[{time:new Date().toLocaleTimeString('zh-CN'),who,result},...prev]);
 const save=()=>{localStorage.setItem('qibox-blue-preview',JSON.stringify(settings));toast('设置已保存到本地预览');log(person.name,'保存回复设置')};
 const row=(key,label,hint,disabled=false)=><div className="option-row" key={key}><span>{label}{hint&&<small>{hint}</small>}</span><Toggle label={label} value={value[key]} disabled={disabled} change={v=>key==='realtime'&&v?setModal('confirm'):update(key,v)}/></div>;
 return <div className="shell"><aside className="sidebar"><a className="brand" href="#" onClick={e=>{e.preventDefault();setPage('reply')}}><span className="brand-icon"><Sparkle size={27} weight="fill"/></span><span>AI 辅助<small>栖盒 · QIBOX</small></span></a><div className="nav-caption">工作空间</div><nav aria-label="AI 页面">{pages.map(([key,label,Icon])=><button key={key} aria-current={page===key?'page':undefined} className={page===key?'active':''} onClick={()=>{setPage(key);setDetail(false)}}><Icon size={23}/><span>{label}</span></button>)}</nav><div className="sidebar-bottom"><div className="account"><span className="account-avatar"><User size={22}/></span><div>我的微信<small>本地设计预览</small></div></div><div className="sidebar-note"><ShieldCheck size={16}/>聊天正文不写入运行记录</div></div></aside>
 <main><header className="topbar"><div className="breadcrumb">AI 辅助<CaretRight size={14}/><strong>{title}</strong></div><div className="top-actions"><span className="preview-label">交互预览 · 示例数据</span><span>AI {master?'已开启':'已关闭'}</span><Toggle label="AI 总开关" value={master} change={setMaster}/></div></header><div className="page-content"><section className="hero"><div><div className="eyebrow">{page==='reply'?'CONVERSATION ASSISTANT':page==='proactive'?'START A CONVERSATION':page==='provider'?'MODEL CONNECTION':'ACTIVITY LOG'}</div><h1>{title}</h1><p>{page==='reply'?'为每个联系人，设置恰到好处的回复方式。':page==='proactive'?'选择聊天对象，配置沟通策略，再一键发起聊天。':page==='provider'?'连接你选择的模型，让 AI 按你的习惯交流。':'查看 AI 的运行状态，及时处理需要你接管的对话。'}</p></div><div className="hero-status"><span className="dot"/>AI 辅助{master?'已就绪':'已暂停'}<small>{master?'按每个对象的设置执行':'开启总开关后继续执行'}</small></div></section>
 {page==='reply'&&<div className={'workspace '+(detail?'detail-open':'')}><section className="card contact-card"><div className="contact-tabs">{[[false,'联系人',User],[true,'群聊',Users]].map(([group,label,Icon])=><button key={label} className={kind===group?'selected':''} onClick={()=>{setKind(group);setSelected(group?'family':'chen')}}><Icon size={18}/>{label}<small>{group?'2':'4'}</small></button>)}</div><label className="search"><MagnifyingGlass size={18}/><input aria-label="搜索联系人或群聊" placeholder="搜索名称…" value={search} onChange={e=>setSearch(e.target.value)}/></label><div className="list-caption">{kind?'我的群聊':'我的联系人'}<button aria-label="刷新对象列表" onClick={()=>toast('示例对象列表已刷新')}><ArrowClockwise size={17}/></button></div><div className="contact-list">{contacts.filter(p=>!!p.group===kind&&p.name.includes(search)).map(p=><button key={p.id} className={'contact-row '+(p.id===selected?'selected':'')} onClick={()=>{setSelected(p.id);setDetail(true)}}><Avatar p={p}/><span>{p.name}<small>{p.note}</small></span><CaretRight size={14}/></button>)}{!contacts.some(p=>!!p.group===kind&&p.name.includes(search))&&<p className="empty">没有找到匹配对象</p>}</div><div className="contact-footer"><label>默认回复范围<select defaultValue="selected" onChange={()=>toast('回复范围已在预览中更新')}><option value="selected">仅已设置的联系人</option><option value="all">所有个人联系人</option></select></label><button className="subtle full" onClick={()=>setModal('batch')}><Sparkle size={17}/>批量学习聊天风格</button></div></section>
 <section className="card detail-card"><button className="subtle mobile-back" onClick={()=>setDetail(false)}><ArrowLeft size={18}/>返回对象列表</button><div className="person-heading"><Avatar p={person} large/><div><h2>{person.name}</h2><p>{person.group?'群聊设置':'联系人设置'}<span>/</span>专属回复策略</p></div><span className="tag">{person.group?'群聊':value.enabled?'自动回复已开启':'自动回复已关闭'}</span></div><section className="setting-section"><h3><ChatCircleText size={20}/>回复方式</h3>{person.group?<div className="group-options">{row('atMe','@我时回复')}{row('atAll','@所有人时回复')}{row('realtime','AI 实时回复')}</div>:<><div className="primary-option">{row('enabled','自动回复','收到新消息时，按照下方风格和要求回复')}</div><div className={'child-options '+(!value.enabled?'disabled':'')}>{row('multi','多轮交流','让对话自然延续',!value.enabled)}{row('judge','智能判断是否回复','在合适的时候回应',!value.enabled)}</div></>}</section><section className="setting-section"><h3><Sparkle size={20}/>聊天风格</h3><div className="style-controls"><select aria-label="选择聊天风格" value={value.style} onChange={e=>update('style',e.target.value)}>{['自然亲切','简洁专业','温暖耐心','已学习的本人风格','自定义风格'].map(x=><option key={x}>{x}</option>)}</select><button className="lavender" onClick={()=>setModal('learn')}><Sparkle size={18}/>学习我的聊天风格</button></div><p className="help">选择常用风格，或从聊天记录中学习你的表达习惯。</p>{value.style==='自定义风格'&&<textarea aria-label="自定义风格" placeholder="描述你的口吻、称呼和表达习惯" value={value.custom||''} onChange={e=>update('custom',e.target.value)}/>}</section><section className="setting-section requirements"><h3><SlidersHorizontal size={20}/>回复要求<span>可选</span></h3><textarea aria-label="回复要求" value={value.goal} onChange={e=>update('goal',e.target.value)} maxLength={1200}/><div className="field-footer"><span>明确回复目的、边界，或需要注意的事情</span><span>{value.goal.length} / 1200</span></div></section><footer className="save-row"><span><ShieldCheck size={16}/>仅应用于当前{person.group?'群聊':'联系人'}</span><button className="primary" onClick={save}><Check size={19}/>保存设置</button></footer></section></div>}
 {page==='proactive'&&<div className="two-column"><section className="card form-card"><h2>发起一次主动聊天</h2><p className="help">一次完成对象选择与策略配置</p><h3>01　选择聊天对象</h3><div className="recipient-grid">{contacts.filter(p=>!p.group).map(p=><label className="recipient" key={p.id}><input type="checkbox" checked={recipients.includes(p.id)} onChange={e=>setRecipients(prev=>e.target.checked?[...prev,p.id]:prev.filter(id=>id!==p.id))}/><Avatar p={p}/>{p.name}</label>)}</div><h3>02　配置沟通策略</h3><label className="field">聊天目标<textarea value={purpose} onChange={e=>setPurpose(e.target.value)} placeholder="例如：问候近况，了解周末是否有空一起吃饭"/></label><div className="field-grid"><label className="field">发送方式<select><option>多轮沟通</option><option>单条发送</option></select></label><label className="field">聊天风格<select><option>使用对象的专属风格</option><option>自然亲切</option><option>简洁专业</option></select></label></div><label className="field">补充信息<textarea placeholder="补充时间、地点、已知信息或沟通边界"/></label><footer className="save-row"><span>已选择 {recipients.length} 位联系人</span><button className="primary" onClick={()=>{if(!recipients.length||!purpose.trim())return toast('请选择联系人并填写聊天目标');setTask('running');log('主动聊天','已创建示例任务');toast('示例任务已开始，不会发送真实消息')}}><PaperPlaneTilt size={18}/>一键发起聊天</button></footer></section><aside className="card form-card task-card"><span className="feature-icon"><PaperPlaneTilt size={26}/></span><h2>执行进度</h2><p className="help">{task==='idle'?'配置完成后，在这里查看联系进度。':task==='running'?'示例任务运行中，等待继续交流。':task==='paused'?'任务已暂停。':'本轮示例任务已结束。'}</p>{task!=='idle'&&<><div className="task-people">{recipients.map(id=><div key={id}><span>{contacts.find(p=>p.id===id).name}</span><span className="tag">{task==='ended'?'已结束':'待联系'}</span></div>)}</div>{task!=='ended'&&<><button className="secondary full" onClick={()=>setTask(task==='running'?'paused':'running')}>{task==='running'?'暂停任务':'继续任务'}</button><button className="subtle full" onClick={()=>setTask('ended')}>结束任务</button></>}</>}</aside></div>}
 {page==='provider'&&<section className="card form-card provider-card"><div className="form-title"><span className="feature-icon"><Lightning size={25}/></span><div><h2>模型连接</h2><p className="help">常用服务与自定义接口，均可自由选择</p></div></div><form onSubmit={e=>{e.preventDefault();toast('预览配置已验证；尚未连接真实模型');log('模型设置','完成示例配置')}}><div className="field-grid"><label className="field">模型服务<select value={provider} onChange={e=>{setProvider(e.target.value);setBase(e.target.value==='DeepSeek'?'https://api.deepseek.com/v1':'');setModel(e.target.value==='DeepSeek'?'deepseek-chat':'')}}><option>DeepSeek</option><option>自定义服务</option></select></label><label className="field">接口类型<select><option>OpenAI 兼容</option><option>Anthropic Messages</option></select></label></div><label className="field">服务地址<input type="url" required value={base} onChange={e=>setBase(e.target.value)} placeholder="https://你的服务地址/v1"/></label><label className="field">API Key<div className="key-input"><input required type={reveal?'text':'password'} placeholder="预览请填写测试文本" autoComplete="off"/><button type="button" aria-label={reveal?'隐藏 API Key':'显示 API Key'} onClick={()=>setReveal(!reveal)}><Eye size={20}/></button></div></label><div className="field-grid"><label className="field">对话模型<input required value={model} onChange={e=>setModel(e.target.value)} placeholder="填写完整模型名称"/></label><label className="field">响应超时（秒）<input type="number" min="10" max="120" defaultValue="60"/></label></div><label className="consent"><input required type="checkbox"/><span>同意将选定聊天发送至所选模型服务，用于学习风格和生成回复。</span></label><p className="help">此页面是设计预览，填写内容不会发送给模型服务，也不会保存 API Key。</p><footer className="save-row"><button type="button" className="secondary" onClick={()=>toast('示例连接通过；真实连接需在正式应用中验证')}>测试连接</button><button className="primary" type="submit"><Check size={18}/>验证并保存</button></footer></form></section>}
 {page==='activity'&&<section className="card form-card"><div className="activity-heading"><h2>最近运行记录</h2><label className="search"><MagnifyingGlass size={18}/><input aria-label="搜索运行记录" placeholder="搜索对象或状态" value={filter} onChange={e=>setFilter(e.target.value)}/></label></div><p className="help">这里仅显示你在本次预览中的操作记录。</p><div className="table-scroll"><table><thead><tr><th>时间</th><th>对象</th><th>运行状态</th><th>类型</th></tr></thead><tbody>{events.filter(e=>(e.who+e.result).includes(filter)).map((e,i)=><tr key={i}><td>{e.time}</td><td>{e.who}</td><td><span className="tag">{e.result}</span></td><td>本地预览</td></tr>)}</tbody></table></div>{!events.filter(e=>(e.who+e.result).includes(filter)).length&&<div className="empty-state"><ClockCounterClockwise size={40}/><h3>暂无运行记录</h3><p>保存回复设置或创建示例任务后，记录会出现在这里。</p></div>}</section>}
 <div className="page-foot">栖盒 AI 辅助<span>让沟通更从容</span></div></div></main>{notice&&<div className="toast" role="status"><Check size={19}/>{notice}</div>}
 {modal&&<div className="modal-backdrop"><section className="modal card" role="dialog" aria-modal="true" aria-labelledby="modal-title"><span className="feature-icon"><Sparkle size={26}/></span><h2 id="modal-title">{modal==='confirm'?'开启群聊实时回复？':modal==='batch'?'批量学习聊天风格':'学习聊天风格'}</h2><p>{modal==='confirm'?'AI 将持续分析群聊消息。消息较多时会增加 Token 用量和费用，频繁自动发言也存在账号风险。':modal==='batch'?'为列表中的全部个人联系人学习专属聊天风格。':'分析与'+person.name+'的聊天，学习你的语气、称呼和表达习惯。'}</p>{modal!=='confirm'&&<><label className="field">学习范围<select><option>最近 100 条聊天</option><option>最近 300 条聊天</option></select></label><p className="help">设计预览仅演示学习结果，不会读取真实聊天。</p></>}<footer className="save-row"><button className="secondary" onClick={()=>setModal('')}>取消</button><button className="primary" onClick={()=>{if(modal==='confirm')update('realtime',true);else if(modal==='batch')setSettings(prev=>({...prev,...Object.fromEntries(contacts.filter(p=>!p.group).map(p=>[p.id,{...defaults,...prev[p.id],style:'已学习的本人风格'}]))}));else update('style','已学习的本人风格');setModal('');toast(modal==='confirm'?'实时回复已在预览中开启':'示例风格已应用，可继续调整回复要求')}}>{modal==='confirm'?'确认开启':'学习并应用'}</button></footer></section></div>}</div>
}
